import type { DashboardStatsDTO, DashboardAttemptDTO, UserProfileDTO } from "@/shared/types/dto"

export const PROFILE_INFO: UserProfileDTO = {
  firstName: "John",
  lastName: "Doe",
  email: "john.doe@example.com",
  registeredAt: "2024-03-05T09:30:00Z",
}

export const DASHBOARD_STATS: DashboardStatsDTO = {
  totalTestsTaken: 24,
  averageScore: 78,
  testsCreated: 8,
  recentActivity: "2026-03-12T10:15:00Z"
}

export const RECENT_ATTEMPTS: DashboardAttemptDTO[] = [
  {
    id: "a1",
    testId: "1",
    testTitle: "JavaScript Fundamentals",
    testCategory: "javascript",
    pointsEarned: 27,
    totalPoints: 30,
    percentage: 90,
    timeTakenSeconds: 1122,
    completedAt: "2026-03-12T16:26:00Z",
    isPassed: true,
  },
  {
    id: "a2",
    testId: "2",
    testTitle: "React Component Patterns",
    testCategory: "react",
    pointsEarned: 19,
    totalPoints: 25,
    percentage: 76,
    timeTakenSeconds: 1335,
    completedAt: "2026-03-11T14:00:00Z",
    isPassed: true,
  },
  {
    id: "a3",
    testId: "4",
    testTitle: "TypeScript Advanced Types",
    testCategory: "typescript",
    pointsEarned: 12,
    totalPoints: 22,
    percentage: 55,
    timeTakenSeconds: 1800,
    completedAt: "2026-03-10T10:15:00Z",
    isPassed: false,
  },
  {
    id: "a4",
    testId: "6",
    testTitle: "SQL & Database Basics",
    testCategory: "databases",
    pointsEarned: 18,
    totalPoints: 20,
    percentage: 90,
    timeTakenSeconds: 873,
    completedAt: "2026-03-09T09:45:00Z",
    isPassed: true,
  },
  {
    id: "a5",
    testId: "1",
    testTitle: "JavaScript Fundamentals",
    testCategory: "javascript",
    pointsEarned: 22,
    totalPoints: 30,
    percentage: 73,
    timeTakenSeconds: 1510,
    completedAt: "2026-03-07T11:20:00Z",
    isPassed: true,
  },
  {
    id: "a6",
    testId: "4",
    testTitle: "TypeScript Advanced Types",
    testCategory: "typescript",
    pointsEarned: 9,
    totalPoints: 22,
    percentage: 41,
    timeTakenSeconds: 1735,
    completedAt: "2026-03-05T08:30:00Z",
    isPassed: false,
  },
  {
    id: "a6",
    testId: "4",
    testTitle: "TypeScript Advanced Types",
    testCategory: "typescript",
    pointsEarned: 9,
    totalPoints: 22,
    percentage: 41,
    timeTakenSeconds: 1735,
    completedAt: "2026-03-05T08:30:00Z",
    isPassed: false,
  },
];