import type { CatalogTestDto } from "@/shared/types/dto";

export const CATALOG_TESTS: CatalogTestDto[] = [
  {
    id: "test_001",
    title: "World Capitals – Quick Fire",
    description: "Basic geography quiz covering capital cities of 50+ countries. Great warm-up for geography lovers.",
    category: "geography",
    difficulty: "easy",
    questionsCount: 50,
    attemptsCount: 12470,
    timeLimitSeconds: 600,
    author: {
      firstName: "Elena",
      lastName: "Martinez",
    },
    ownership: "public",
    createdAt: "2024-11-12T14:30:00Z",
  },

  {
    id: "test_002",
    title: "JavaScript & TypeScript Core Concepts",
    description: "Covers closures, prototypes, async/await, generics, utility types, type guards, discriminated unions and more.",
    category: "programming",
    difficulty: "medium",
    questionsCount: 38,
    attemptsCount: 3842,
    timeLimitSeconds: 1200,
    author: {
      firstName: "Alex",
      lastName: "Chen",
    },
    ownership: "public",
    createdAt: "2025-02-08T09:15:00Z",
  },

  {
    id: "test_003",
    title: "My Custom React + Zustand Interview Prep",
    description: "Questions I collected while preparing for senior frontend interviews in 2025",
    category: "programming",
    difficulty: "hard",
    questionsCount: 22,
    attemptsCount: 17,
    timeLimitSeconds: 900,
    author: {
      firstName: "Sophie",
      lastName: "Kowalski",
    },
    ownership: "mine",
    createdAt: "2026-03-10T18:42:00Z",
  },

  {
    id: "test_004",
    title: "Organic Chemistry – Functional Groups & Reactions",
    description: "Focuses on nomenclature, reaction mechanisms, stereochemistry and common named reactions.",
    category: "chemistry",
    difficulty: "hard",
    questionsCount: 45,
    attemptsCount: 2891,
    timeLimitSeconds: 1500,
    author: {
      firstName: "Dr. James",
      lastName: "Patel",
    },
    ownership: "public",
    createdAt: "2024-06-30T11:20:00Z",
  },

  {
    id: "test_005",
    title: "Medical School – Year 1 Anatomy Recall",
    description: "Basic gross anatomy, neuroanatomy and embryology questions for first-year medical students.",
    category: "medicine",
    difficulty: "medium",
    questionsCount: 80,
    attemptsCount: 634,
    timeLimitSeconds: 1800,
    author: {
      firstName: "Maya",
      lastName: "Rodriguez",
    },
    ownership: "public",
    createdAt: "2025-09-05T07:45:00Z",
  },

  {
    id: "test_006",
    title: "1980s & 1990s Music Trivia",
    description: "From MTV golden era to grunge, boy bands and early hip-hop. How well do you remember?",
    category: "music",
    difficulty: "easy",
    questionsCount: 60,
    attemptsCount: 15780,
    timeLimitSeconds: 900,
    author: {
      firstName: "Lucas",
      lastName: "Becker",
    },
    ownership: "public",
    createdAt: "2024-12-24T15:10:00Z",
  },

  {
    id: "test_007",
    title: "LeetCode Top 150 – Blind 75 + Extras (2025 edition)",
    description: "Curated selection of the most frequently asked medium/hard problems with updated patterns.",
    category: "programming",
    difficulty: "hard",
    questionsCount: 92,
    attemptsCount: 421,
    timeLimitSeconds: 3600,
    author: {
      firstName: "Daniel",
      lastName: "Kim",
    },
    ownership: "mine",
    createdAt: "2026-03-18T22:05:00Z",
  },

  {
    id: "test_008",
    title: "Ancient Civilizations – Mesopotamia to Rome",
    description: "Timeline, rulers, inventions, architecture and fall of major ancient civilizations.",
    category: "history",
    difficulty: "medium",
    questionsCount: 55,
    attemptsCount: 3921,
    timeLimitSeconds: 1200,
    author: {
      firstName: "Prof. Aisha",
      lastName: "Malik",
    },
    ownership: "public",
    createdAt: "2025-01-17T10:55:00Z",
  },

  {
    id: "test_009",
    title: "SQL for Data Analysts – Window Functions & CTEs",
    description: "Heavy focus on RANK/DENSE_RANK, LAG/LEAD, recursive CTEs, pivoting and complex joins.",
    category: "data_science",
    difficulty: "hard",
    questionsCount: 28,
    attemptsCount: 943,
    timeLimitSeconds: 1800,
    author: {
      firstName: "Liam",
      lastName: "Nguyen",
    },
    ownership: "public",
    createdAt: "2025-11-03T13:25:00Z",
  },

  {
    id: "test_010",
    title: "Random Knowledge Battle – Mixed Bag #7",
    description: "Completely random questions from physics, movies, biology, memes, geography and pop culture.",
    category: "general_knowledge",
    difficulty: "medium",
    questionsCount: 100,
    attemptsCount: 28764,
    timeLimitSeconds: 2000,
    author: {
      firstName: "QuizMaster",
      lastName: "42",
    },
    ownership: "public",
    createdAt: "2026-02-14T08:00:00Z",
  },
];